apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    run: frontend
spec:
  ports:
  - port: 15002
    protocol: TCP
  - port: 15003
    protocol: TCP
  selector:
    run: frontend